language: rust
rust:
        - stable
        - beta
        - nightly
matrix:
        allow_failures:
                - rust: stable
cache: cargo
script:
        - cargo build --verbose --all --features clippy
