[package]
name = "argmin"
version = "0.0.0"
authors = ["Stefan Kroboth <stefan.kroboth@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "WIP optimization toolbox for Rust"
documentation = "https://stefan-k.github.io/argmin-rs/argmin/"
homepage = "https://github.com/stefan-k/argmin-rs"
repository = "https://github.com/stefan-k/argmin-rs"
readme = "README.md"
keywords = ["optimization", "math", "science", "HPC"]
categories = ["science"]
#license-file = "LICENSE-APACHE"
exclude = [ 
	".travis.yml",
	"push_docs",
]

[dependencies]
argmin_core = { path = "../argmin-core" }
argmin_derive = { path = "../argmin-derive" }
argmin_linesearch = { path = "../argmin-linesearch" }
argmin_gradientdescent = { path = "../argmin-gradientdescent" }
argmin_testfunctions = { path = "../argmin-testfunctions" }
rand = "*"


[features]
default = []

[badges]
travis-ci = { repository = "argmin-rs/argmin", branch = "master" }
