[package]
name = "argmin"
version = "0.0.0"
authors = ["Stefan Kroboth <stefan.kroboth@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "WIP optimization toolbox for Rust"
documentation = "https://stefan-k.github.io/argmin-rs/argmin/"
homepage = "https://github.com/stefan-k/argmin-rs"
repository = "https://github.com/stefan-k/argmin-rs"
readme = "README.md"
keywords = ["optimization", "math", "science", "HPC"]
categories = ["science"]
#license-file = "LICENSE-APACHE"
exclude = [ 
	".travis.yml",
	"push_docs",
]

[dependencies]
# ndarray = "*"
# ndarray-linalg = { version = "*", features = ["openblas"] }
# argmin_simulatedannealing = { git = "https://github.com/argmin-rs/argmin-simulatedannealing.git" }
argmin_core = { path = "../argmin-core" }
argmin_simulatedannealing = { path = "../argmin-simulatedannealing" }
argmin_conjugategradient = { path = "../argmin-conjugategradient" }


[features]
default = []

[badges]
travis-ci = { repository = "argmin-rs/argmin", branch = "master" }
