[package]
name = "argmin"
version = "0.1.0"
authors = ["Stefan Kroboth <stefan.kroboth@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "WIP optimization toolbox for Rust"
documentation = "https://argmin-rs.github.io/argmin/argmin/"
homepage = "https://github.com/argmin-rs/argmin"
repository = "https://github.com/argmin-rs/argmin"
readme = "README.md"
keywords = ["optimization", "math", "science", "HPC"]
categories = ["science"]
#license-file = "LICENSE-APACHE"
exclude = [ 
	".travis.yml",
	"push_docs",
]

[dependencies]
# argmin_core = { path = "../argmin-core" }
# argmin_codegen = { path = "../argmin-codegen" }
# argmin_testfunctions = { path = "../argmin-testfunctions" }
argmin_core = { git = "https://github.com/argmin-rs/argmin-core.git" }
# argmin_core = "0.1.1"
argmin_codegen = "0.1.0"
argmin_testfunctions = "0.1.0"
rand = "0.5.5"


[features]
default = []

[badges]
travis-ci = { repository = "argmin-rs/argmin", branch = "master" }
