[package]
name = "argmin"
version = "0.0.0"
authors = ["Stefan Kroboth <stefan.kroboth@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Optimization algorithms"
documentation = "https://stefan-k.github.io/rust/argmin/"
homepage = "https://github.com/stefan-k/argmin-rs"
repository = "https://github.com/stefan-k/argmin-rs"
readme = "README.md"
keywords = ["optimization", "math", "science", "HPC"]
categories = ["science"]
#license-file = "LICENSE-APACHE"

[dependencies]
clippy = {version = "*", optional = true}
error-chain = "*"
num = "*"
rand = "*"
ndarray = "*"
#ndarray-linalg = { version = "*", default-features = openblas }
ndarray-linalg = { version = "*", features = ["openblas"] }

[features]
default = []
