[package]
name = "argmin"
version = "0.1.7"
authors = ["Stefan Kroboth <stefan.kroboth@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A pure Rust toolbox/framework for numerical optimization"
documentation = "https://argmin-rs.github.io/argmin/argmin/"
homepage = "https://github.com/argmin-rs/argmin"
repository = "https://github.com/argmin-rs/argmin"
readme = "README.md"
keywords = ["optimization", "math", "science", "HPC"]
categories = ["science"]
#license-file = "LICENSE-APACHE"
exclude = [
	".travis.yml",
	"push_docs",
]

[dependencies]
argmin_core = { path = "../argmin-core"}
argmin_codegen = { path = "../argmin-codegen"}
argmin_testfunctions = { path = "../argmin-testfunctions" }
# argmin_core = { git = "https://github.com/argmin-rs/argmin-core.git", branch = "master"}
# argmin_codegen = { git = "https://github.com/argmin-rs/argmin-codegen.git", branch = "master"}
# argmin_testfunctions = { git = "https://github.com/argmin-rs/argmin-testfunctions.git", branch = "master"}
#argmin_core = "0.1.7"
#argmin_codegen = "0.1.7"
#argmin_testfunctions = "0.1.1"
rand = "0.6.1"
serde = { version = "1.0", features = ["derive", "rc"] }

[dev-dependencies]
ndarray = { version = "0.12.1", features = ["serde-1"] }
ndarray-linalg = { version = "0.10.0", features = ["openblas"] }
gnuplot = "0.0.27"
paste = "0.1.4"


[features]
default = []
ctrlc = ["argmin_core/ctrlc"]
ndarrayl = ["argmin_core/ndarrayl"]

[badges]
travis-ci = { repository = "argmin-rs/argmin", branch = "master" }
